include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    undefined_prefixed_name: ignore

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
