name: admanager_web
description: Simple package that allow us display ads from Ad Manager in Flutter Web. This was primarily created to display Adsense ads on Flutter Web.
version: 0.0.4
homepage: https://github.com/nathanael540/admanager_web

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.4.0+2
  universal_html: ^2.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
